mappings:
  ConsentFormExtension: Mouseketeers\ConsentForms\ConsentFormExtension
  EditableConsentCheckbox: Mouseketeers\ConsentForms\EditableConsentCheckbox
  ConsentCheckboxField: Mouseketeers\ConsentForms\ConsentCheckboxField
